name: find_me
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  app_settings: ^5.1.1
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  flutter_map: ^4.0.0
  fluttertoast: ^8.2.3
  geolocator: ^10.1.0
  http: ^0.13.6
  mapbox_gl: ^0.16.0
  permission_handler: ^11.0.1

  telephony:
    git:
      url: https://github.com/suhardik/s_telephony.git
      ref: develop
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/find.jpg
    - assets/find.png
